use mydb;

show databases;CREATE DATABASE `SqlTest` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE DATABASE `SqlTest` /*!40100 DEFAULT CHARACTER SET utf8 */;

CREATE TABLE `game` (
  `gameid` int(11) NOT NULL,
  `game_name` varchar(45) NOT NULL DEFAULT 'M' COMMENT 'M: MaJiang\nP: Poker',
  `type` varchar(45) NOT NULL,
  `region` varchar(45) DEFAULT NULL COMMENT 'The region where people this game, such as Beijing, Shanghai, Shijiazhuang, etc.',
  `min_players` int(11) DEFAULT NULL,
  `max_players` varchar(45) DEFAULT NULL,
  `server_ip` varchar(45) DEFAULT NULL,
  `server_port` int(11) DEFAULT NULL,
  PRIMARY KEY (`gameid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `room` (
  `userid` int(11) NOT NULL,
  `gameid` int(11) NOT NULL,
  `room_no` varchar(10) DEFAULT NULL,
  `round_num` int(11) DEFAULT NULL,
  `ex_ip_cheat` int(11) DEFAULT '0' COMMENT '1, players from same network IP can not in same room\n0, every one can enter this room, there is not test in IP',
  `ex_gps_cheat` int(11) DEFAULT '0' COMMENT 'Default 0: no test in player’s gps location\n1: two people is too near in gps, can not in same room',
  `fee_stuff_id` int(11) DEFAULT NULL,
  `fee_amount_per_player` tinyint(8) DEFAULT NULL,
  `fee_creator_pay_all` tinyint(4) DEFAULT NULL COMMENT '1, the creator pay the total fee\n0, all the player pay the total fee in the average way',
  `stake_stuff_id` int(11) DEFAULT NULL COMMENT 'The stuff which will be won or lost in the game, for example diamonds, golden coin, silver coin, shell etc\n',
  `stake_base_score` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `stuff` (
  `stuffid` int(11) NOT NULL AUTO_INCREMENT,
  `stuffname` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`stuffid`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8;

CREATE TABLE `stuff_exchange` (
  `stuffid1` int(11) NOT NULL,
  `stuffid2` int(11) DEFAULT NULL,
  `id1_to_id2_ratio` decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (`stuffid1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user` (
  `userid` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(45) DEFAULT NULL COMMENT 'Generated by database, started with “LX” then 6 digitals',
  `phone` varchar(20) DEFAULT NULL,
  `password` varchar(45) DEFAULT NULL,
  `alias` varchar(45) DEFAULT NULL,
  `image` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8;

CREATE TABLE `user_device` (
  `userid` int(11) NOT NULL,
  `device` varchar(128) DEFAULT NULL,
  `valid` int(11) DEFAULT '1' COMMENT '0, invalid , an illegal device\n1, valid, legal device'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_login` (
  `userid` int(11) NOT NULL,
  `device` varchar(128) NOT NULL,
  `session_token` varchar(256) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `user_stuff` (
  `userid` int(11) NOT NULL,
  `stuffid` int(11) NOT NULL,
  `amount` int(11) DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


