source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'LXQEnjoy' do
    pod 'SnapKit', '~> 4.0'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'SDWebImage', '~> 4.0'
end
